export const prod = {
  isSSOAuthEnabled: false,
  baseUrl: "https://prod.fd.1silverbullet.tech/api/v1",
  dashboard: "",
  login: "/login",

  getCustomer: "/customers?customer_pan=1234567890",
  updateCustomer: "/customer",
  createCustomer: "/customer",
  getCustomerDetails: "/customer/details?user_id=",

  getUserDetails: "/user/details",
  getProducts: "/products?manufacturer_ids=2&product_type=FD&product_id=1",
  addProducts: "/products",
  updateProducts: "/products",
  getProductList: "/products/list",
  getProductDetail: "/product/details",
  getComparePlans: "/products/compare",

  viewFd: "/fd?user_id=",
  updateFd: "/fd",
  getAllFd: "/fds?user_id=",
  bookFd: "/fd/book_fd",
  commitFd: "/fd/commit",
  do_payment: "/fd/payment/redirection",
  withdrawFd: "/fd/closeWithdraw",
  fdHistory: "/fd/history?user_id=&fd_id=2",
  ckycVerification: "/ckyc",
  generateOTP: "/otp/generate",
  verifyOTP: "/otp/verify",
  makePayment: "/payment",
  getAllAttachedManufacturer: "/manufacturer?dictributor_id=",
  getNominee: "/nominee?user_id=",
  addNominee: "/nominee",
  updateNominee: "/nominee",
  deleteNominee: "/nominee",
  getBankDetail: "/bank_detail?user_id=",
  addBankDetail: "/bank_detail",
  updateBankDetail: "/bank_detail",
  deleteBankDetail: "/bank_detail",
  bankVerify: "/bank_detail",
  getBankbyIfsc: "/bank_details_through_ifsc?",
  zipCode: "/zip_code_detail?consumerId=1&ZIPCODE=",
  fdCalculator: "/fd_calculator",
  pennyDrop: "/penny_drop",
  updatePaymentDetails: "/updatePaymentDetails",
  diclaimer: "/application/setup?distributor_id=",
  bankLogoBaseUrl:
    "https://1sb-manufacturer-logos.s3.ap-south-1.amazonaws.com/fixed-deposit/bankLogos/",
  redirectURLAfterLogout: "/",

  tenureMaster: "/tenuremaster",
  applicationStatus: "/applicationStatus?fdId=",
};
